controller_manager:
  ros__parameters:
    # INCREASED to 100Hz for smoother control loop
    update_rate: 100
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    # INCREASED to 50Hz for smoother TF (Less shaking in RViz)
    publish_rate: 50.0
    
    odom_topic: /odom
    odom_frame_id: odom
    base_frame_id: base_footprint
    publish_odom_tf: true

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.297
    wheel_radius: 0.035

    use_stamped_vel: false

    # SAFETY: Stop the robot if no command received for 0.5 seconds
    # This prevents the robot from running away if the teleop crashes
    cmd_vel_timeout: 0.5
    
    # LIMITS: (Optional) Un-comment these to prevent wheelies
    # linear.x.has_velocity_limits: true
    # linear.x.max_velocity: 0.4
    # linear.x.min_velocity: -0.4
    # linear.x.max_acceleration: 1.0